apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
  namespace: expense
data: 
  DB_HOST: mysql

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  # labels of deployment resource
  labels:
    app: backend
    tier: backend
    project: expense
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
      tier: backend
      project: expense
  template:
    metadata:
      labels:
        app: backend
        tier: backend
        project: expense
    spec:
      containers:
      - name: nginx
        image: dakshina2025/backend:1.0.0
        envFrom:
        - ConfigMapRef:
            name: backend
---
kind: Service
apiVersion: v1
metadata:
  name: backend
  namespace: expense
spec:
  selector: # labels are used as selectors
    app: backend
    tier: backend
    project: expense
  ports:
  - protocol: TCP
    port: 8080 #service port
    targetPort: 8080
        